- name: Deploy Lambda Function and API Gateway
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install AWS CLI
      become: yes
      pip:
        name: awscli

    - name: Set AWS environment variables
      shell: echo "export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.bashrc && echo "export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.bashrc
      environment:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Configure AWS CLI
      environment:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      command: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-west-2

    - name: Deploy Lambda Function
      environment:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      command: aws lambda create-function --function-name ${LAMBDA_FUNCTION_NAME} --runtime python3.8 --handler ${LAMBDA_HANDLER} --role ${LAMBDA_ROLE} --zip-file fileb://${LAMBDA_ZIP_FILE}

    - name: Create API Gateway
      environment:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      command: aws apigatewayv2 create-api --name ${API_GATEWAY_NAME} --protocol-type HTTP --target ${API_GATEWAY_TARGET} --region us-west-2

    - name: Create API Gateway Integration
      environment:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      command: aws apigatewayv2 create-integration --api-id ${API_GATEWAY_API_ID} --integration-type AWS_PROXY --integration-method POST --integration-uri arn:aws:lambda:us-west-2:${AWS_ACCOUNT_ID}:function:${LAMBDA_FUNCTION_NAME}:${LAMBDA_QUALIFIER} --payload-format-version 2.0 --region us-west-2

    - name: Create API Gateway Route
      environment:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      command: aws apigatewayv2 create-route --api-id ${API_GATEWAY_API_ID} --route-key ${API_GATEWAY_ROUTE_KEY} --target integrations/${API_GATEWAY_INTEGRATION_ID} --region us-west-2

    - name: Create API Gateway Deployment
      environment:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      command: aws apigatewayv2 create-deployment --api-id ${API_GATEWAY_API_ID} --region us-west-2

    - name: Print API Gateway URL
      environment:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      command: aws apigatewayv2 get-apis --query 'Items[?Name==`${API_GATEWAY_NAME}`].ApiEndpoint' --output text --region us-west-2
