name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create lambda_code.zip
      run: |
          zip lambda_code.zip helloworld.py


    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws lambda create-function --function-name helloworld02 \
            --runtime python3.8 \
            --zip-file fileb://lambda_code.zip \
            --handler lambda_function.lambda_handler \
            --role arn:aws:iam::847105105358:role/mcdaniel_lambda \
            --region ${{ secrets.AWS_REGION }}

    - name: Deploy to API Gateway
      run: |
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        export AWS_REGION="${{ secrets.AWS_REGION }}"
        aws apigateway create-rest-api --name helloworld02 \
          --endpoint-configuration types=REGIONAL