name: Deploy Lambda Function and API Gateway
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip install ansible

      - name: Deploy using Ansible
        run: ansible-playbook -i 127.0.0.1, deploy.yml --connection=local
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          s3_bucket: ${{ secrets.S3_BUCKET }}
          stack_name: ${{ secrets.STACK_NAME }}
          api_gateway_stage: ${{ secrets.API_GATEWAY_STAGE }}
